# Generated by Django 3.2.4 on 2021-06-30 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0002_rename_portfolio_userprofileinfo_portfolio_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileinfo',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1),
        ),
    ]
